// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	"github.com/enbility/zeroconf/v3/api"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConnectionFactory creates a new instance of MockConnectionFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnectionFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnectionFactory {
	mock := &MockConnectionFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConnectionFactory is an autogenerated mock type for the ConnectionFactory type
type MockConnectionFactory struct {
	mock.Mock
}

type MockConnectionFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnectionFactory) EXPECT() *MockConnectionFactory_Expecter {
	return &MockConnectionFactory_Expecter{mock: &_m.Mock}
}

// CreateIPv4Conn provides a mock function for the type MockConnectionFactory
func (_mock *MockConnectionFactory) CreateIPv4Conn(ifaces []net.Interface) (api.PacketConn, error) {
	ret := _mock.Called(ifaces)

	if len(ret) == 0 {
		panic("no return value specified for CreateIPv4Conn")
	}

	var r0 api.PacketConn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]net.Interface) (api.PacketConn, error)); ok {
		return returnFunc(ifaces)
	}
	if returnFunc, ok := ret.Get(0).(func([]net.Interface) api.PacketConn); ok {
		r0 = returnFunc(ifaces)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.PacketConn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]net.Interface) error); ok {
		r1 = returnFunc(ifaces)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionFactory_CreateIPv4Conn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIPv4Conn'
type MockConnectionFactory_CreateIPv4Conn_Call struct {
	*mock.Call
}

// CreateIPv4Conn is a helper method to define mock.On call
//   - ifaces []net.Interface
func (_e *MockConnectionFactory_Expecter) CreateIPv4Conn(ifaces interface{}) *MockConnectionFactory_CreateIPv4Conn_Call {
	return &MockConnectionFactory_CreateIPv4Conn_Call{Call: _e.mock.On("CreateIPv4Conn", ifaces)}
}

func (_c *MockConnectionFactory_CreateIPv4Conn_Call) Run(run func(ifaces []net.Interface)) *MockConnectionFactory_CreateIPv4Conn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []net.Interface
		if args[0] != nil {
			arg0 = args[0].([]net.Interface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionFactory_CreateIPv4Conn_Call) Return(packetConn api.PacketConn, err error) *MockConnectionFactory_CreateIPv4Conn_Call {
	_c.Call.Return(packetConn, err)
	return _c
}

func (_c *MockConnectionFactory_CreateIPv4Conn_Call) RunAndReturn(run func(ifaces []net.Interface) (api.PacketConn, error)) *MockConnectionFactory_CreateIPv4Conn_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIPv6Conn provides a mock function for the type MockConnectionFactory
func (_mock *MockConnectionFactory) CreateIPv6Conn(ifaces []net.Interface) (api.PacketConn, error) {
	ret := _mock.Called(ifaces)

	if len(ret) == 0 {
		panic("no return value specified for CreateIPv6Conn")
	}

	var r0 api.PacketConn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]net.Interface) (api.PacketConn, error)); ok {
		return returnFunc(ifaces)
	}
	if returnFunc, ok := ret.Get(0).(func([]net.Interface) api.PacketConn); ok {
		r0 = returnFunc(ifaces)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.PacketConn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]net.Interface) error); ok {
		r1 = returnFunc(ifaces)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConnectionFactory_CreateIPv6Conn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIPv6Conn'
type MockConnectionFactory_CreateIPv6Conn_Call struct {
	*mock.Call
}

// CreateIPv6Conn is a helper method to define mock.On call
//   - ifaces []net.Interface
func (_e *MockConnectionFactory_Expecter) CreateIPv6Conn(ifaces interface{}) *MockConnectionFactory_CreateIPv6Conn_Call {
	return &MockConnectionFactory_CreateIPv6Conn_Call{Call: _e.mock.On("CreateIPv6Conn", ifaces)}
}

func (_c *MockConnectionFactory_CreateIPv6Conn_Call) Run(run func(ifaces []net.Interface)) *MockConnectionFactory_CreateIPv6Conn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []net.Interface
		if args[0] != nil {
			arg0 = args[0].([]net.Interface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConnectionFactory_CreateIPv6Conn_Call) Return(packetConn api.PacketConn, err error) *MockConnectionFactory_CreateIPv6Conn_Call {
	_c.Call.Return(packetConn, err)
	return _c
}

func (_c *MockConnectionFactory_CreateIPv6Conn_Call) RunAndReturn(run func(ifaces []net.Interface) (api.PacketConn, error)) *MockConnectionFactory_CreateIPv6Conn_Call {
	_c.Call.Return(run)
	return _c
}
