// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInterfaceProvider creates a new instance of MockInterfaceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterfaceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterfaceProvider {
	mock := &MockInterfaceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInterfaceProvider is an autogenerated mock type for the InterfaceProvider type
type MockInterfaceProvider struct {
	mock.Mock
}

type MockInterfaceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterfaceProvider) EXPECT() *MockInterfaceProvider_Expecter {
	return &MockInterfaceProvider_Expecter{mock: &_m.Mock}
}

// MulticastInterfaces provides a mock function for the type MockInterfaceProvider
func (_mock *MockInterfaceProvider) MulticastInterfaces() []net.Interface {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MulticastInterfaces")
	}

	var r0 []net.Interface
	if returnFunc, ok := ret.Get(0).(func() []net.Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]net.Interface)
		}
	}
	return r0
}

// MockInterfaceProvider_MulticastInterfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MulticastInterfaces'
type MockInterfaceProvider_MulticastInterfaces_Call struct {
	*mock.Call
}

// MulticastInterfaces is a helper method to define mock.On call
func (_e *MockInterfaceProvider_Expecter) MulticastInterfaces() *MockInterfaceProvider_MulticastInterfaces_Call {
	return &MockInterfaceProvider_MulticastInterfaces_Call{Call: _e.mock.On("MulticastInterfaces")}
}

func (_c *MockInterfaceProvider_MulticastInterfaces_Call) Run(run func()) *MockInterfaceProvider_MulticastInterfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterfaceProvider_MulticastInterfaces_Call) Return(interfaces []net.Interface) *MockInterfaceProvider_MulticastInterfaces_Call {
	_c.Call.Return(interfaces)
	return _c
}

func (_c *MockInterfaceProvider_MulticastInterfaces_Call) RunAndReturn(run func() []net.Interface) *MockInterfaceProvider_MulticastInterfaces_Call {
	_c.Call.Return(run)
	return _c
}
