// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPacketConn creates a new instance of MockPacketConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPacketConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPacketConn {
	mock := &MockPacketConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPacketConn is an autogenerated mock type for the PacketConn type
type MockPacketConn struct {
	mock.Mock
}

type MockPacketConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPacketConn) EXPECT() *MockPacketConn_Expecter {
	return &MockPacketConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockPacketConn
func (_mock *MockPacketConn) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPacketConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPacketConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPacketConn_Expecter) Close() *MockPacketConn_Close_Call {
	return &MockPacketConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPacketConn_Close_Call) Run(run func()) *MockPacketConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPacketConn_Close_Call) Return(err error) *MockPacketConn_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPacketConn_Close_Call) RunAndReturn(run func() error) *MockPacketConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// JoinGroup provides a mock function for the type MockPacketConn
func (_mock *MockPacketConn) JoinGroup(ifi *net.Interface, group net.Addr) error {
	ret := _mock.Called(ifi, group)

	if len(ret) == 0 {
		panic("no return value specified for JoinGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*net.Interface, net.Addr) error); ok {
		r0 = returnFunc(ifi, group)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPacketConn_JoinGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinGroup'
type MockPacketConn_JoinGroup_Call struct {
	*mock.Call
}

// JoinGroup is a helper method to define mock.On call
//   - ifi *net.Interface
//   - group net.Addr
func (_e *MockPacketConn_Expecter) JoinGroup(ifi interface{}, group interface{}) *MockPacketConn_JoinGroup_Call {
	return &MockPacketConn_JoinGroup_Call{Call: _e.mock.On("JoinGroup", ifi, group)}
}

func (_c *MockPacketConn_JoinGroup_Call) Run(run func(ifi *net.Interface, group net.Addr)) *MockPacketConn_JoinGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *net.Interface
		if args[0] != nil {
			arg0 = args[0].(*net.Interface)
		}
		var arg1 net.Addr
		if args[1] != nil {
			arg1 = args[1].(net.Addr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPacketConn_JoinGroup_Call) Return(err error) *MockPacketConn_JoinGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPacketConn_JoinGroup_Call) RunAndReturn(run func(ifi *net.Interface, group net.Addr) error) *MockPacketConn_JoinGroup_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveGroup provides a mock function for the type MockPacketConn
func (_mock *MockPacketConn) LeaveGroup(ifi *net.Interface, group net.Addr) error {
	ret := _mock.Called(ifi, group)

	if len(ret) == 0 {
		panic("no return value specified for LeaveGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*net.Interface, net.Addr) error); ok {
		r0 = returnFunc(ifi, group)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPacketConn_LeaveGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveGroup'
type MockPacketConn_LeaveGroup_Call struct {
	*mock.Call
}

// LeaveGroup is a helper method to define mock.On call
//   - ifi *net.Interface
//   - group net.Addr
func (_e *MockPacketConn_Expecter) LeaveGroup(ifi interface{}, group interface{}) *MockPacketConn_LeaveGroup_Call {
	return &MockPacketConn_LeaveGroup_Call{Call: _e.mock.On("LeaveGroup", ifi, group)}
}

func (_c *MockPacketConn_LeaveGroup_Call) Run(run func(ifi *net.Interface, group net.Addr)) *MockPacketConn_LeaveGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *net.Interface
		if args[0] != nil {
			arg0 = args[0].(*net.Interface)
		}
		var arg1 net.Addr
		if args[1] != nil {
			arg1 = args[1].(net.Addr)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPacketConn_LeaveGroup_Call) Return(err error) *MockPacketConn_LeaveGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPacketConn_LeaveGroup_Call) RunAndReturn(run func(ifi *net.Interface, group net.Addr) error) *MockPacketConn_LeaveGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFrom provides a mock function for the type MockPacketConn
func (_mock *MockPacketConn) ReadFrom(b []byte) (int, int, net.Addr, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for ReadFrom")
	}

	var r0 int
	var r1 int
	var r2 net.Addr
	var r3 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, int, net.Addr, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) int); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func([]byte) net.Addr); ok {
		r2 = returnFunc(b)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(net.Addr)
		}
	}
	if returnFunc, ok := ret.Get(3).(func([]byte) error); ok {
		r3 = returnFunc(b)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockPacketConn_ReadFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFrom'
type MockPacketConn_ReadFrom_Call struct {
	*mock.Call
}

// ReadFrom is a helper method to define mock.On call
//   - b []byte
func (_e *MockPacketConn_Expecter) ReadFrom(b interface{}) *MockPacketConn_ReadFrom_Call {
	return &MockPacketConn_ReadFrom_Call{Call: _e.mock.On("ReadFrom", b)}
}

func (_c *MockPacketConn_ReadFrom_Call) Run(run func(b []byte)) *MockPacketConn_ReadFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPacketConn_ReadFrom_Call) Return(n int, ifIndex int, src net.Addr, err error) *MockPacketConn_ReadFrom_Call {
	_c.Call.Return(n, ifIndex, src, err)
	return _c
}

func (_c *MockPacketConn_ReadFrom_Call) RunAndReturn(run func(b []byte) (int, int, net.Addr, error)) *MockPacketConn_ReadFrom_Call {
	_c.Call.Return(run)
	return _c
}

// SetMulticastHopLimit provides a mock function for the type MockPacketConn
func (_mock *MockPacketConn) SetMulticastHopLimit(hopLimit int) error {
	ret := _mock.Called(hopLimit)

	if len(ret) == 0 {
		panic("no return value specified for SetMulticastHopLimit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(hopLimit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPacketConn_SetMulticastHopLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMulticastHopLimit'
type MockPacketConn_SetMulticastHopLimit_Call struct {
	*mock.Call
}

// SetMulticastHopLimit is a helper method to define mock.On call
//   - hopLimit int
func (_e *MockPacketConn_Expecter) SetMulticastHopLimit(hopLimit interface{}) *MockPacketConn_SetMulticastHopLimit_Call {
	return &MockPacketConn_SetMulticastHopLimit_Call{Call: _e.mock.On("SetMulticastHopLimit", hopLimit)}
}

func (_c *MockPacketConn_SetMulticastHopLimit_Call) Run(run func(hopLimit int)) *MockPacketConn_SetMulticastHopLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPacketConn_SetMulticastHopLimit_Call) Return(err error) *MockPacketConn_SetMulticastHopLimit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPacketConn_SetMulticastHopLimit_Call) RunAndReturn(run func(hopLimit int) error) *MockPacketConn_SetMulticastHopLimit_Call {
	_c.Call.Return(run)
	return _c
}

// SetMulticastInterface provides a mock function for the type MockPacketConn
func (_mock *MockPacketConn) SetMulticastInterface(ifi *net.Interface) error {
	ret := _mock.Called(ifi)

	if len(ret) == 0 {
		panic("no return value specified for SetMulticastInterface")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*net.Interface) error); ok {
		r0 = returnFunc(ifi)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPacketConn_SetMulticastInterface_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMulticastInterface'
type MockPacketConn_SetMulticastInterface_Call struct {
	*mock.Call
}

// SetMulticastInterface is a helper method to define mock.On call
//   - ifi *net.Interface
func (_e *MockPacketConn_Expecter) SetMulticastInterface(ifi interface{}) *MockPacketConn_SetMulticastInterface_Call {
	return &MockPacketConn_SetMulticastInterface_Call{Call: _e.mock.On("SetMulticastInterface", ifi)}
}

func (_c *MockPacketConn_SetMulticastInterface_Call) Run(run func(ifi *net.Interface)) *MockPacketConn_SetMulticastInterface_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *net.Interface
		if args[0] != nil {
			arg0 = args[0].(*net.Interface)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPacketConn_SetMulticastInterface_Call) Return(err error) *MockPacketConn_SetMulticastInterface_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPacketConn_SetMulticastInterface_Call) RunAndReturn(run func(ifi *net.Interface) error) *MockPacketConn_SetMulticastInterface_Call {
	_c.Call.Return(run)
	return _c
}

// SetMulticastTTL provides a mock function for the type MockPacketConn
func (_mock *MockPacketConn) SetMulticastTTL(ttl int) error {
	ret := _mock.Called(ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetMulticastTTL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPacketConn_SetMulticastTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMulticastTTL'
type MockPacketConn_SetMulticastTTL_Call struct {
	*mock.Call
}

// SetMulticastTTL is a helper method to define mock.On call
//   - ttl int
func (_e *MockPacketConn_Expecter) SetMulticastTTL(ttl interface{}) *MockPacketConn_SetMulticastTTL_Call {
	return &MockPacketConn_SetMulticastTTL_Call{Call: _e.mock.On("SetMulticastTTL", ttl)}
}

func (_c *MockPacketConn_SetMulticastTTL_Call) Run(run func(ttl int)) *MockPacketConn_SetMulticastTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPacketConn_SetMulticastTTL_Call) Return(err error) *MockPacketConn_SetMulticastTTL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPacketConn_SetMulticastTTL_Call) RunAndReturn(run func(ttl int) error) *MockPacketConn_SetMulticastTTL_Call {
	_c.Call.Return(run)
	return _c
}

// WriteTo provides a mock function for the type MockPacketConn
func (_mock *MockPacketConn) WriteTo(b []byte, ifIndex int, dst net.Addr) (int, error) {
	ret := _mock.Called(b, ifIndex, dst)

	if len(ret) == 0 {
		panic("no return value specified for WriteTo")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, int, net.Addr) (int, error)); ok {
		return returnFunc(b, ifIndex, dst)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, int, net.Addr) int); ok {
		r0 = returnFunc(b, ifIndex, dst)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, int, net.Addr) error); ok {
		r1 = returnFunc(b, ifIndex, dst)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPacketConn_WriteTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTo'
type MockPacketConn_WriteTo_Call struct {
	*mock.Call
}

// WriteTo is a helper method to define mock.On call
//   - b []byte
//   - ifIndex int
//   - dst net.Addr
func (_e *MockPacketConn_Expecter) WriteTo(b interface{}, ifIndex interface{}, dst interface{}) *MockPacketConn_WriteTo_Call {
	return &MockPacketConn_WriteTo_Call{Call: _e.mock.On("WriteTo", b, ifIndex, dst)}
}

func (_c *MockPacketConn_WriteTo_Call) Run(run func(b []byte, ifIndex int, dst net.Addr)) *MockPacketConn_WriteTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 net.Addr
		if args[2] != nil {
			arg2 = args[2].(net.Addr)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPacketConn_WriteTo_Call) Return(n int, err error) *MockPacketConn_WriteTo_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPacketConn_WriteTo_Call) RunAndReturn(run func(b []byte, ifIndex int, dst net.Addr) (int, error)) *MockPacketConn_WriteTo_Call {
	_c.Call.Return(run)
	return _c
}
